brew "git"
brew "vim"
brew "jq"
brew "tree"
brew "yarn"

cask "visual-studio-code"
cask "coteditor"
cask "github"
cask "google-chrome"
cask "firefox"
cask "docker"
cask "slack"
cask "zoom"
cask "discord"
cask "Notion"
cask "bitwarden"
cask "appcleaner"

tap "homebrew/cask-fonts"
cask "font-mononoki-nerd-font"