# ===========================================
# system
brew 'git'
brew 'jq'
brew 'tree'
brew 'yarn'
brew 'curl'
brew 'wget'
brew 'libyaml'

brew 'mas'
brew 'starship'
brew 'neovim'
brew 'lazydocker'


# ===========================================
# develop
cask 'warp'
cask 'visual-studio-code'
cask 'coteditor'
cask 'github'
cask 'docker'
cask 'postman'
cask 'tableplus'
cask 'altair-graphql-client'

# social
cask 'google-chrome'
cask 'google-drive'
cask 'slack'
cask 'discord'
cask 'zoom'
cask 'notion'
cask 'cron'

# util
cask '1password'
cask 'appcleaner'
cask 'the-unarchiver'
cask 'balenaetcher'

# system
cask 'alt-tab'
cask 'skitch'
cask 'rectangle'
cask 'karabiner-elements'
cask 'scroll-reverser'
cask 'hiddenbar'


# ===========================================
# mac app store
mas "LanScan", id: 472226235
mas "RunCat", id: 1429033973
mas "Spaced", id: 1666327168
mas "MagicNotch", id: 6447055708
