# Based on Nord theme
# https://github.com/nordtheme/alacritty/blob/main/src/nord.yaml

[colors]
background       = '#2e3440'
foreground       = '#d8dee9'
dim-foreground   = '#d8dee9'
light-foreground = '#d8dee9'

cursor           = '#d8dee9'

tabs             = '#494c62'
tabs-active      = '#6a6e8e'

black            = '#3b4252'
blue             = '#81a1c1'
cyan             = '#88c0d0'
green            = '#a3be8c'
magenta          = '#b48ead'
red              = '#bf616a'
white            = '#e5e9f0'
yellow           = '#ebcb8b'

dim-black        = '#373e4d'
dim-blue         = '#68809a'
dim-cyan         = '#6d96a5'
dim-green        = '#809575'
dim-magenta      = '#8c738c'
dim-red          = '#94545d'
dim-white        = '#aeb3bb'
dim-yellow       = '#b29e75'

light-black      = '#4c566a'
light-blue       = '#81a1c1'
light-cyan       = '#8fbcbb'
light-green      = '#a3be8c'
light-magenta    = '#b48ead'
light-red        = '#bf616a'
light-white      = '#eceff4'
light-yellow     = '#ebcb8b'
