# https://raphamorim.io/rio/docs/config/


# Theme
theme = "warp"

# Padding
padding-x = 20
padding-y = [0, 10]

# Line height
# There is padding bug if line-height is set :(
# line-height = 1.2

[editor]
program = "code"
args = []

[cursor]
shape = 'beam'
blinking = true
blinking-interval = 600

[window]
width = 1500
height = 700
mode = "Windowed"
opacity = 0.8
blur = true
decorations = "Enabled"

[renderer]
performance = "High"
backend = "Automatic"
disable-renderer-when-unfocused = false

[fonts]
family = "Cica"
size = 20

[scroll]
multiplier = 3.0
divider = 1.0

[navigation]
mode = "Bookmark"
clickable = true
hide-if-single = true
use-current-path = true
color-automation = []

[bindings]
# More information in: https://raphamorim.io/rio/docs/config/bindings
keys = [
  { key = "d", with = "super", action = "SplitHorizontally" },
]
